import { chromium } from 'playwright';
import { writeFileSync } from 'fs';

async function takeScreenshots() {
    console.log('🎬 Starting Playwright screenshot session...');

    const browser = await chromium.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const context = await browser.newContext({
        viewport: { width: 1920, height: 1080 },
    });

    const page = await context.newPage();

    try {
        // Upewnij się, że serwer Vite działa
        console.log('⏳ Waiting for Vite server to be ready...');
        await page.goto('http://localhost:5173', {
            waitUntil: 'networkidle',
            timeout: 30000,
        });

        console.log('✅ Vite server is ready');

        // Dashboard
        console.log('📸 Screenshot 1: Dashboard...');
        await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
        await page.waitForTimeout(3000); // Czekaj na animacje
        await page.screenshot({ path: 'screenshots/dashboard.png', fullPage: true });
        console.log('✅ Dashboard screenshot saved');

        // Brain Map
        console.log('📸 Screenshot 2: Brain Map...');
        await page.goto('http://localhost:5173/brain', { waitUntil: 'networkidle' });
        await page.waitForTimeout(3000);
        await page.screenshot({ path: 'screenshots/brain-map.png', fullPage: true });
        console.log('✅ Brain Map screenshot saved');

        // System Status
        console.log('📸 Screenshot 3: System Status...');
        await page.goto('http://localhost:5173/status', { waitUntil: 'networkidle' });
        await page.waitForTimeout(3000);
        await page.screenshot({ path: 'screenshots/system-status.png', fullPage: true });
        console.log('✅ System Status screenshot saved');

        // Mobile viewport test (Dashboard)
        console.log('📸 Screenshot 4: Dashboard (Mobile)...');
        await page.setViewportSize({ width: 375, height: 667 });
        await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
        await page.waitForTimeout(2000);
        await page.screenshot({ path: 'screenshots/dashboard-mobile.png', fullPage: true });
        console.log('✅ Dashboard (Mobile) screenshot saved');

        // Generate report
        const report = `
# VISION LOOP - Quality Assurance Report

Generated: ${new Date().toISOString()}
Dashboard: ZeroClaw Crystal View

## Screenshots Captured

1. **Dashboard** - \`screenshots/dashboard.png\`
   - Status: ✅ Captured
   - Viewport: Desktop (1920x1080)

2. **Brain Map** - \`screenshots/brain-map.png\`
   - Status: ✅ Captured
   - Viewport: Desktop (1920x1080)

3. **System Status** - \`screenshots/system-status.png\`
   - Status: ✅ Captured
   - Viewport: Desktop (1920x1080)

4. **Dashboard (Mobile)** - \`screenshots/dashboard-mobile.png\`
   - Status: ✅ Captured
   - Viewport: Mobile (375x667)

## Visual Checklist

- [ ] All elements are visible and not cut off
- [ ] Sidebar navigation is accessible
- [ ] Charts are rendering correctly
- [ ] Glassmorphism effects are working
- [ ] Text is readable on all backgrounds
- [ ] Mobile layout is responsive
- [ ] No JavaScript errors in console

## Issues Found

*Review screenshots manually to identify any visual issues.*

---
*Generated by ZeroClaw Vision Loop*
`;

        writeFileSync('screenshots/vision-loop-report.md', report);
        console.log('📄 Vision Loop report saved');

    } catch (error) {
        console.error('❌ Error during screenshot session:', error);
        throw error;
    } finally {
        await context.close();
        await browser.close();
        console.log('🎬 Playwright session completed');
    }
}

// Run if executed directly
takeScreenshots().catch((error) => {
    console.error('Screenshot session failed:', error);
    process.exit(1);
});

export { takeScreenshots };
